### ISSUE TITLE
Error building with Xcode - ld: -pie can only be used when targeting iOS 4.2 or later

### ISSUE THREAD

**Issue by adammendoza** [watmough/Calc41C#1]
I'm trying to build this for iPhone 6 and iOS 8.3 and I get this error. Ideas how to some this?

Thanks!

Ld /Users/adam/Library/Developer/Xcode/DerivedData/Calc41C-ddxsxitxikqsvxalgvelwbsymrvj/Build/Products/Debug-iphonesimulator/Calc41C.app/Calc41C normal i386
    cd /Users/adam/code/xcode/Calc41C
    export IPHONEOS_DEPLOYMENT_TARGET=3.1.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -L/Users/adam/Library/Developer/Xcode/DerivedData/Calc41C-ddxsxitxikqsvxalgvelwbsymrvj/Build/Products/Debug-iphonesimulator -F/Users/adam/Library/Developer/Xcode/DerivedData/Calc41C-ddxsxitxikqsvxalgvelwbsymrvj/Build/Products/Debug-iphonesimulator -filelist /Users/adam/Library/Developer/Xcode/DerivedData/Calc41C-ddxsxitxikqsvxalgvelwbsymrvj/Build/Intermediates/Calc41C.build/Debug-iphonesimulator/Calc41C.build/Objects-normal/i386/Calc41C.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=3.1.3 -framework Foundation -framework UIKit -framework CoreGraphics -framework AudioToolbox -Xlinker -dependency_info -Xlinker /Users/adam/Library/Developer/Xcode/DerivedData/Calc41C-ddxsxitxikqsvxalgvelwbsymrvj/Build/Intermediates/Calc41C.build/Debug-iphonesimulator/Calc41C.build/Objects-normal/i386/Calc41C_dependency_info.dat -o /Users/adam/Library/Developer/Xcode/DerivedData/Calc41C-ddxsxitxikqsvxalgvelwbsymrvj/Build/Products/Debug-iphonesimulator/Calc41C.app/Calc41C

ld: -pie can only be used when targeting iOS 4.2 or later
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by watmough** [comment]
Prob have an old build target in there.

**Comment by watmough** [comment]
FYI: Setting it to target iOS 7.0 fixes this. Just doing some bug-fixes
myself.

**Comment by watmough** [comment]
Resolved by setting build target to iOS 7.0

**Comment by watmough** [comment]
Adam,

Please try the latest update. Many bugs fixed.

Best Wishes,
Jonathan
